### ISSUE TITLE
Wildcard Certifcates are not supported.

### ISSUE THREAD

**Issue by tobidemski** [astrixsystems/Update-hMailServerCertificate#1]
Heys guys,

i'm trying to use your script as an post step in my certify the web app for one domain.
I tried to execute your script (1.12) the first time via powershell but i got an error.

> [ERROR]: Could not update hMailServer's SSL / TLS certificate.
The filename, directory name, or volume label syntax is incorrect. 0x8007007b (WIN32/HTTP: 123 ERROR_INVALID_NAME)

I'm using a wildcard certificate. (*.mydomain.com).

After adding ".Replace("*","_")" in line 344 the script works fine.
Windows does not allow to create files with an asteriks in the filename.
Maybe you can update the script to support wildcard certs?

Best regards and thanks for the script so far!
Tobi

**Comment by benhooperastrix** [comment]
Hi @D4rkiii,

Thanks for reaching out and apologies for the delay - I only saw this a few days ago.

I've created and tested version v1.13 to fix this. Below is a demonstration screenshot:
![2019-10-01_15-14-16 - Update-hMailServerCertificate v1 13 with wildcard certificate](https://user-images.githubusercontent.com/44265685/65970350-48be4a80-e45e-11e9-8760-ff0db055b79c.png)

We're in the process of renewing our code signing certificate at the moment so I'll post it and let you know as soon as possible.

Thanks,

Ben.

**Comment by benhooperastrix** [comment]
Hi @D4rkiii,

Sorry for the delay. Our CA took a **long** time to re-issue our code signing certificate for some reason.

I've now signed and uploaded v1.13 to https://github.com/astrixsystems/Update-hMailServerCertificate/blob/master/Update-hMailServerCertificate%20v1.13.ps1

Thanks,

Ben.
